name: base
channels:
 - conda-forge
 - default
dependencies:
 - zarr
 - xarray
 - numpy
 - dask
 - distributed
 - bokeh
 - panel
 - holoviews
 - pandas
 - scipy
 - scikit-image
 - numcodecs
 - s3fs
 - lz4
 - pip
 - pip:
     - imaxt-image
